### ISSUE TITLE
distinguisch 5 stars

### ISSUE THREAD

**Issue by schillerenrico** [dimi777/diablo-rift-simulator#1]
@dimi777 
https://gamerswiki.net/diablo-immortal-5-star-gem-drop-rate/

Looks like the drop rate is 5% for a 5 Star.
Could you distinguisch between the stars that the 5 star drop has?
Cause quin is looking for a 5 star drop with 5 stars. Thats a 1 in 100 5star drops.

Could look like this:
![image](https://user-images.githubusercontent.com/10064004/174396826-c8ae0d6c-31db-4900-8122-7a80a9f53a9a.png)

**Comment by diablo-rift-simulator** [comment]
@schillerenrico the "5 stars gem" only shows the amount of 5/5 gems, same as quin69 stream.

**Comment by diablo-rift-simulator** [comment]
Additional info will be added later :)

**Comment by diablo-rift-simulator** [comment]
@schillerenrico check out the newest release :)
