### ISSUE TITLE
How would you know the odds?

### ISSUE THREAD

**Issue by balayanv** [dimi777/diablo-rift-simulator#3]
I dont think they are stupid enough to publish the code for this, it must be somewhere in the backend, not in android or ios code...
Just curious because otherwise this is just deceptive...

**Comment by diablo-rift-simulator** [comment]
![legendary-crest-gem-drop-rates](https://user-images.githubusercontent.com/24569488/174447025-050a410f-7e4f-4603-a9a4-53397ff38c5c.png)
You can click a button to see the odds while doing the Elder Rift.

**Comment by balayanv** [comment]
lol
